#!/bin/sh

# these lines are for work desktop, to make middle mouse scroll on click
xinput --set-prop 10 "Evdev Wheel Emulation" 1
xinput --set-prop 10 "Evdev Wheel Emulation Button" 2
xinput --set-prop 10 "Evdev Wheel Emulation Axes" 6 7 4 5

# invoke xfce session script
. /etc/xdg/xfce4/xinitrc
